# -*- coding: utf-8 -*-
"""Day4Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-rfppTBnnASdicUD-rCZKE3zBw96aB6
"""
lower=1042000
upper=702648265
for i in range(lower, upper+1):
	order=len(str(i))
	temp = i
	sum=0
	while temp>0:
		digit = temp%10
		sum=sum+digit**order
		temp//= 10

	if sum == i:
		print(i,"is the first armstrong number between 1042000 and 702648265")
		break
